#$ -cwd
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  AU565 --left    AU565_paired_R1.fq.gz    --right AU565_paired_R2.fq.gz  --prep_reference 
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  HCC1937 --left    HCC1937_paired_R1.fq.gz    --right HCC1937_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  MDAMB231 --left    MDAMB231_paired_R1.fq.gz    --right MDAMB231_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  MDAMB453 --left    MDAMB453_paired_R1.fq.gz    --right MDAMB453_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  T47D --left    T47D_paired_R1.fq.gz    --right T47D_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  HCC_1395 --left    HCC_1395_paired_R1.fq.gz    --right HCC_1395_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  HCC1954 --left    HCC1954_paired_R1.fq.gz    --right HCC1954_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  MDAMB361 --left    MDAMB361_paired_R1.fq.gz    --right MDAMB361_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  SKBR3 --left    SKBR3_paired_R1.fq.gz    --right SKBR3_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  ZR751 --left    ZR751_paired_R1.fq.gz    --right ZR751_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  HCC_1806 --left    HCC_1806_paired_R1.fq.gz    --right HCC_1806_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  MCF7 --left    MCF7_paired_R1.fq.gz    --right MCF7_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  MDAMB415 --left    MDAMB415_paired_R1.fq.gz    --right MDAMB415_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  SKBR3 --left    SKBR3_paired_R1.fq.gz    --right SKBR3_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util//align_and_estimate_abundance.pl --transcripts nt_human.fa    --est_method salmon  --seqType fq  --thread_count    16 --output_dir  ZR75B --left    ZR75B_paired_R1.fq.gz    --right ZR75B_paired_R2.fq.gz
/shelf/apps/pjt6/apps/trinityrnaseq-Trinity-v2.8.4/util/abundance_estimates_to_matrix.pl --est_method salmon --gene_trans_map  none --name_sample_by_basedir --out_prefix nt_human.fa.genes.counts.matrix AU565/quant.sf HCC1937/quant.sf MDAMB231/quant.sf MDAMB453/quant.sf T47D/quant.sf HCC_1395/quant.sf HCC1954/quant.sf MDAMB361/quant.sf SKBR3/quant.sf ZR751/quant.sf HCC_1806/quant.sf MCF7/quant.sf MDAMB415/quant.sf SKBR3/quant.sf ZR75B/quant.sf  
